#!/usr/bin/env bash
# Installing the load balancer


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 531237-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 531237-web-02 34.239.107.22:80 check\n\tserver 531237-web-01 100.24.205.222:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start